ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS logic_version_id uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS last_assistant_acknowledged_at timestamptz;
ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.envelopes ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.hints ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.hint_sheets ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.project_storyboards ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.canvas_nodes ADD COLUMN IF NOT EXISTS logic_version_id uuid;
ALTER TABLE public.canvas_edges ADD COLUMN IF NOT EXISTS logic_version_id uuid;
UPDATE public.documents d SET logic_version_id = p.logic_version_id FROM public.projects p WHERE d.project_id = p.id AND d.logic_version_id IS NULL;
UPDATE public.envelopes e SET logic_version_id = p.logic_version_id FROM public.projects p WHERE e.project_id = p.id AND e.logic_version_id IS NULL;
UPDATE public.hints h SET logic_version_id = p.logic_version_id FROM public.projects p WHERE h.project_id = p.id AND h.logic_version_id IS NULL;
UPDATE public.hint_sheets h SET logic_version_id = p.logic_version_id FROM public.projects p WHERE h.project_id = p.id AND h.logic_version_id IS NULL;
UPDATE public.project_storyboards s SET logic_version_id = p.logic_version_id FROM public.projects p WHERE s.project_id = p.id AND s.logic_version_id IS NULL;
UPDATE public.canvas_nodes n SET logic_version_id = p.logic_version_id FROM public.projects p WHERE n.project_id = p.id AND n.logic_version_id IS NULL;
UPDATE public.canvas_edges c SET logic_version_id = p.logic_version_id FROM public.projects p WHERE c.project_id = p.id AND c.logic_version_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_documents_logic_version ON public.documents(project_id, logic_version_id);
CREATE INDEX IF NOT EXISTS idx_envelopes_logic_version ON public.envelopes(project_id, logic_version_id);
CREATE INDEX IF NOT EXISTS idx_hints_logic_version ON public.hints(project_id, logic_version_id);
CREATE INDEX IF NOT EXISTS idx_canvas_nodes_logic_version ON public.canvas_nodes(project_id, logic_version_id);
CREATE INDEX IF NOT EXISTS idx_project_storyboards_logic_version ON public.project_storyboards(project_id, logic_version_id);